version: '3.5'
services:
  #### HTTP_PROXY ####
  development_http_proxy:
    image: httpd:latest
    networks:
      - logigator_intern
    volumes:
      - ./docker/development/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./docker/development/ca.crt:/usr/local/apache2/conf/server.crt
      - ./docker/development/private.key:/usr/local/apache2/conf/server.key
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
  #### NODE_JS_BACKEND_HOME ####
  development_backend:
    image: node:12
    networks:
      logigator_intern:
        aliases:
          - backend
    depends_on:
      - development_mysql
    volumes:
      - ./logigator-backend/:/home/node/app
    user: "node"
    working_dir: /home/node/app
    command: "npm start"
    environment:
      - DEBUG=express:*
      - DEBUG_COLORS=on
  #### MYSQL ####
  development_mysql:
    image: mysql:latest
    networks:
      logigator_intern:
        aliases:
          - mysql
    ports:
      - "127.0.0.1:3306:3306"
    cap_add:
      - SYS_NICE
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=logigator
      - MYSQL_USER=logigator
      - MYSQL_PASSWORD=logigator
  #### REDIS ####
  development_redis:
    image: redis:latest
    networks:
      logigator_intern:
        aliases:
          - redis
  #### REDIS_UI ####
  development_redis_ui:
    image: marian/rebrow:latest
    networks:
      - logigator_intern
    ports:
      - "127.0.0.1:5001:5001"
  #### NODE_JS_EDITOR ####
  development_editor:
    image: node:12
    networks:
      logigator_intern:
        aliases:
          - editor
    volumes:
      - ./logigator-editor/:/home/node/app
    user: "node"
    working_dir: /home/node/app
    command: "npm start"

networks:
  logigator_intern:
    driver: bridge
